name: bexdeliveries
description: A new Flutter project.
publish_to: 'none'
version: 1.3.135+259
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  location_repository:
    path: packages/location_repository

  charger_status:
    path: plugins/charger_status

  #icons
  cupertino_icons: ^1.0.2
  #permission
  permission_handler: ^10.2.0
  device_info_plus: ^8.2.2
  #network
  dio: ^5.0.2
  #state management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  shared_preferences: ^2.0.18
  meta: ^1.8.0
  flutter_secure_storage: ^8.0.0
  #locations
  location: ^5.0.0
  latlong2: ^0.8.1
  geolocator: ^10.1.0
  #connectivy
  connectivity_plus: ^3.0.3
  #map
  map_launcher: ^2.5.0+1
  flutter_map: ^3.1.0
  flutter_map_tile_caching: ^7.2.0
  fmtc_plus_background_downloading: ^7.0.0
  fmtc_plus_sharing: ^7.0.0
  osm_nominatim: ^2.0.1
  #database
  synchronized: ^3.0.1
  sqflite: ^2.2.6
  sqlbrite: ^2.6.0
  sqflite_migration: ^0.3.0
  #others
  awesome_snackbar_content: ^0.1.3
  equatable: ^2.0.5
  path_provider: ^2.0.13
  lottie: ^2.3.0
  yaml: ^3.1.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.2
  showcaseview: ^2.0.2
  flutter_udid: ^2.0.1
  flutter_spinkit: ^5.2.0
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.0.4
  mockito: ^5.4.2
  intl: ^0.18.0
  vibration: ^1.7.6
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  validators: ^3.0.0
  camera: ^0.10.5
  image: ^3.3.0
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  readmore: ^2.2.0
  routing_client_dart: ^0.5.3
  #download regions
  better_open_file: ^3.6.4
  version: ^3.0.2
  flutter_speed_dial: ^6.2.0
  badges: ^3.0.3
  path: ^1.8.2
  stream_transform: ^2.1.0
  flutter_svg: ^2.0.5
  flutter_slidable: ^3.0.0
  dynamic_color: ^1.6.5
  collection: ^1.17.1
  #firebase
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  firebase_remote_config: ^4.3.3
  overlay_support: ^2.1.0
  cloud_functions: ^4.3.3
  firebase_analytics: ^10.4.3
  logging: ^1.2.0
  firebase_crashlytics: ^3.4.4
  font_awesome_flutter: ^10.5.0
  flutter_web_browser: ^0.17.1
  whatsapp_unilink: ^2.1.0
  flutter_local_notifications: ^13.0.0

dependency_overrides:
  isar: 3.0.6-dev.0
  isar_flutter_libs: 3.0.6-dev.0
  hive: ^3.0.0-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  build_runner: ^2.4.6
  bloc_test: ^9.1.5
  hive_generator:
    git:
      url: https://github.com/hivedb/hive
      path: hive_generator

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/launcher/
    - assets/animations/
    - assets/icons/
    - pubspec.yaml
  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_Bold.ttf
        - asset: assets/fonts/Butler_Light.ttf
        - asset: assets/fonts/Butler_Regular.ttf
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf

