name: bexdeliveries
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  location_repository:
    path: packages/location_repository

  #icons
  cupertino_icons: ^1.0.2
  #permission
  permission_handler: ^10.2.0
  #network
  dio: ^5.0.2
  #state managment
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  shared_preferences: ^2.0.18
  meta: ^1.8.0
  #locations
  location: ^4.4.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  #connectivy
  connectivity_plus: ^3.0.3
  #map
  map_launcher: ^2.5.0+1
  flutter_map: ^3.1.0
  flutter_map_tile_caching: ^7.2.0
  fmtc_plus_background_downloading: ^7.0.0
  fmtc_plus_sharing: ^7.0.0
  osm_nominatim: ^2.0.1
  #database
  synchronized: ^3.0.1
  sqflite: ^2.2.6
  sqlbrite: ^2.6.0
  sqflite_migration: ^0.3.0
  #others
  equatable: ^2.0.5
  path_provider: ^2.0.13
  lottie: ^2.3.0
  yaml: ^3.1.1
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.10
  showcaseview: ^2.0.2
  flutter_udid: ^2.0.1
  intl: ^0.18.0
  vibration: ^1.7.6
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  validators: ^3.0.0
  camera: ^0.10.3+2
  #download regions

  better_open_file: ^3.6.4
  version: ^3.0.2
  flutter_speed_dial: ^6.2.0
  badges: ^3.0.3
  hive: ^2.2.3
  path: ^1.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.bexdeliveries
        pluginClass: ChargerStatusPlugin
      ios:
        pluginClass: ChargerStatusPlugin
  uses-material-design: true
  assets:
    - assets/images/
    - assets/launcher/
    - assets/animations/
    - assets/icons/
    - pubspec.yaml
  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_Bold.ttf
        - asset: assets/fonts/Butler_Light.ttf
        - asset: assets/fonts/Butler_Regular.ttf
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf

