// Mocks generated by Mockito 5.4.4 from annotations
// in bexdeliveries/test/cubits/home/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:bexdeliveries/core/helpers/index.dart' as _i4;
import 'package:bexdeliveries/src/domain/models/account.dart' as _i18;
import 'package:bexdeliveries/src/domain/models/client.dart' as _i24;
import 'package:bexdeliveries/src/domain/models/error.dart' as _i23;
import 'package:bexdeliveries/src/domain/models/history_order.dart' as _i25;
import 'package:bexdeliveries/src/domain/models/location.dart' as _i19;
import 'package:bexdeliveries/src/domain/models/news.dart' as _i11;
import 'package:bexdeliveries/src/domain/models/note.dart' as _i22;
import 'package:bexdeliveries/src/domain/models/notification.dart' as _i27;
import 'package:bexdeliveries/src/domain/models/photo.dart' as _i21;
import 'package:bexdeliveries/src/domain/models/processing_queue.dart' as _i2;
import 'package:bexdeliveries/src/domain/models/reason.dart' as _i17;
import 'package:bexdeliveries/src/domain/models/requests/account_request.dart'
    as _i37;
import 'package:bexdeliveries/src/domain/models/requests/client_request.dart'
    as _i52;
import 'package:bexdeliveries/src/domain/models/requests/database_request.dart'
    as _i45;
import 'package:bexdeliveries/src/domain/models/requests/enterprise_config_request.dart'
    as _i33;
import 'package:bexdeliveries/src/domain/models/requests/enterprise_request.dart'
    as _i31;
import 'package:bexdeliveries/src/domain/models/requests/history_order_saved_request.dart'
    as _i57;
import 'package:bexdeliveries/src/domain/models/requests/history_order_updated_request.dart'
    as _i61;
import 'package:bexdeliveries/src/domain/models/requests/locations_request.dart'
    as _i62;
import 'package:bexdeliveries/src/domain/models/requests/login_request.dart'
    as _i39;
import 'package:bexdeliveries/src/domain/models/requests/logout_request.dart'
    as _i41;
import 'package:bexdeliveries/src/domain/models/requests/prediction_request.dart'
    as _i55;
import 'package:bexdeliveries/src/domain/models/requests/reason_m_request.dart'
    as _i63;
import 'package:bexdeliveries/src/domain/models/requests/reason_request.dart'
    as _i35;
import 'package:bexdeliveries/src/domain/models/requests/routing_request.dart'
    as _i59;
import 'package:bexdeliveries/src/domain/models/requests/send_token.dart'
    as _i53;
import 'package:bexdeliveries/src/domain/models/requests/status_request.dart'
    as _i47;
import 'package:bexdeliveries/src/domain/models/requests/transaction_request.dart'
    as _i49;
import 'package:bexdeliveries/src/domain/models/requests/transaction_summary_request.dart'
    as _i50;
import 'package:bexdeliveries/src/domain/models/requests/work_request.dart'
    as _i43;
import 'package:bexdeliveries/src/domain/models/responses/account_response.dart'
    as _i36;
import 'package:bexdeliveries/src/domain/models/responses/database_response.dart'
    as _i44;
import 'package:bexdeliveries/src/domain/models/responses/enterprise_config_response.dart'
    as _i32;
import 'package:bexdeliveries/src/domain/models/responses/enterprise_response.dart'
    as _i30;
import 'package:bexdeliveries/src/domain/models/responses/history_order_saved_response.dart'
    as _i56;
import 'package:bexdeliveries/src/domain/models/responses/history_order_updated_response.dart'
    as _i60;
import 'package:bexdeliveries/src/domain/models/responses/login_response.dart'
    as _i38;
import 'package:bexdeliveries/src/domain/models/responses/logout_response.dart'
    as _i40;
import 'package:bexdeliveries/src/domain/models/responses/prediction_response.dart'
    as _i54;
import 'package:bexdeliveries/src/domain/models/responses/reason_response.dart'
    as _i34;
import 'package:bexdeliveries/src/domain/models/responses/routing_response.dart'
    as _i58;
import 'package:bexdeliveries/src/domain/models/responses/status_response.dart'
    as _i46;
import 'package:bexdeliveries/src/domain/models/responses/transaction_response.dart'
    as _i48;
import 'package:bexdeliveries/src/domain/models/responses/transaction_summary_response.dart'
    as _i51;
import 'package:bexdeliveries/src/domain/models/responses/work_response.dart'
    as _i42;
import 'package:bexdeliveries/src/domain/models/summary.dart' as _i13;
import 'package:bexdeliveries/src/domain/models/summary_report.dart' as _i14;
import 'package:bexdeliveries/src/domain/models/transaction.dart' as _i15;
import 'package:bexdeliveries/src/domain/models/transaction_summary.dart'
    as _i16;
import 'package:bexdeliveries/src/domain/models/warehouse.dart' as _i12;
import 'package:bexdeliveries/src/domain/models/work.dart' as _i10;
import 'package:bexdeliveries/src/domain/repositories/api_repository.dart'
    as _i29;
import 'package:bexdeliveries/src/domain/repositories/database_repository.dart'
    as _i8;
import 'package:bexdeliveries/src/presentation/blocs/gps/gps_bloc.dart' as _i6;
import 'package:bexdeliveries/src/presentation/blocs/network/network_bloc.dart'
    as _i7;
import 'package:bexdeliveries/src/presentation/blocs/processing_queue/processing_queue_bloc.dart'
    as _i5;
import 'package:bexdeliveries/src/utils/resources/data_state.dart' as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i64;
import 'package:geolocator/geolocator.dart' as _i65;
import 'package:latlong2/latlong.dart' as _i28;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;
import 'package:sqflite/sqflite.dart' as _i26;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProcessingQueue_0 extends _i1.SmartFake
    implements _i2.ProcessingQueue {
  _FakeProcessingQueue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataState_1<T> extends _i1.SmartFake implements _i3.DataState<T> {
  _FakeDataState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHelperFunctions_2 extends _i1.SmartFake
    implements _i4.HelperFunctions {
  _FakeHelperFunctions_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProcessingQueueState_3 extends _i1.SmartFake
    implements _i5.ProcessingQueueState {
  _FakeProcessingQueueState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGpsState_4 extends _i1.SmartFake implements _i6.GpsState {
  _FakeGpsState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkState_5 extends _i1.SmartFake implements _i7.NetworkState {
  _FakeNetworkState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseRepository extends _i1.Mock
    implements _i8.DatabaseRepository {
  MockDatabaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i10.Work>> getAllWorks() => (super.noSuchMethod(
        Invocation.method(
          #getAllWorks,
          [],
        ),
        returnValue: _i9.Future<List<_i10.Work>>.value(<_i10.Work>[]),
      ) as _i9.Future<List<_i10.Work>>);

  @override
  _i9.Future<List<_i10.Work>> findAllWorksByWorkcode(String? workcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #findAllWorksByWorkcode,
          [workcode],
        ),
        returnValue: _i9.Future<List<_i10.Work>>.value(<_i10.Work>[]),
      ) as _i9.Future<List<_i10.Work>>);

  @override
  _i9.Future<List<_i10.Work>> findAllWorksPaginatedByWorkcode(
    String? workcode,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findAllWorksPaginatedByWorkcode,
          [
            workcode,
            page,
          ],
        ),
        returnValue: _i9.Future<List<_i10.Work>>.value(<_i10.Work>[]),
      ) as _i9.Future<List<_i10.Work>>);

  @override
  _i9.Future<List<String>?> completeWorks() => (super.noSuchMethod(
        Invocation.method(
          #completeWorks,
          [],
        ),
        returnValue: _i9.Future<List<String>?>.value(),
      ) as _i9.Future<List<String>?>);

  @override
  _i9.Future<int> countAllWorksByWorkcode(String? workcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #countAllWorksByWorkcode,
          [workcode],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> insertWork(_i10.Work? work) => (super.noSuchMethod(
        Invocation.method(
          #insertWork,
          [work],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateWork(_i10.Work? work) => (super.noSuchMethod(
        Invocation.method(
          #updateWork,
          [work],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateStatusWork(
    String? workcode,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatusWork,
          [
            workcode,
            status,
          ],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertWorks(List<_i10.Work>? works) => (super.noSuchMethod(
        Invocation.method(
          #insertWorks,
          [works],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyWorks() => (super.noSuchMethod(
        Invocation.method(
          #emptyWorks,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteWorksByWorkcode(String? workcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorksByWorkcode,
          [workcode],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i10.WorkTypes?> getWorkTypesFromWorkcode(String? workcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkTypesFromWorkcode,
          [workcode],
        ),
        returnValue: _i9.Future<_i10.WorkTypes?>.value(),
      ) as _i9.Future<_i10.WorkTypes?>);

  @override
  _i9.Future<List<_i10.WorkAdditional>> getClientsResJetDel(
    String? workcode,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClientsResJetDel,
          [
            workcode,
            reason,
          ],
        ),
        returnValue: _i9.Future<List<_i10.WorkAdditional>>.value(
            <_i10.WorkAdditional>[]),
      ) as _i9.Future<List<_i10.WorkAdditional>>);

  @override
  _i9.Future<void> insertNews(_i11.News? news) => (super.noSuchMethod(
        Invocation.method(
          #insertNews,
          [news],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i12.Warehouse>> getAllWarehouses() => (super.noSuchMethod(
        Invocation.method(
          #getAllWarehouses,
          [],
        ),
        returnValue: _i9.Future<List<_i12.Warehouse>>.value(<_i12.Warehouse>[]),
      ) as _i9.Future<List<_i12.Warehouse>>);

  @override
  _i9.Future<_i12.Warehouse?> findWarehouse(int? id) => (super.noSuchMethod(
        Invocation.method(
          #findWarehouse,
          [id],
        ),
        returnValue: _i9.Future<_i12.Warehouse?>.value(),
      ) as _i9.Future<_i12.Warehouse?>);

  @override
  _i9.Future<int> insertWarehouse(_i12.Warehouse? warehouse) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWarehouse,
          [warehouse],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateWarehouse(_i12.Warehouse? warehouse) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWarehouse,
          [warehouse],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertWarehouses(List<_i12.Warehouse>? warehouses) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWarehouses,
          [warehouses],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyWarehouses() => (super.noSuchMethod(
        Invocation.method(
          #emptyWarehouses,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i13.Summary>> getAllSummariesByOrderNumber(int? workId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSummariesByOrderNumber,
          [workId],
        ),
        returnValue: _i9.Future<List<_i13.Summary>>.value(<_i13.Summary>[]),
      ) as _i9.Future<List<_i13.Summary>>);

  @override
  _i9.Future<List<_i13.Summary>> getAllSummariesByWorkcode(
    int? workId,
    String? customer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSummariesByWorkcode,
          [
            workId,
            customer,
          ],
        ),
        returnValue: _i9.Future<List<_i13.Summary>>.value(<_i13.Summary>[]),
      ) as _i9.Future<List<_i13.Summary>>);

  @override
  _i9.Future<List<_i13.Summary>> getAllInventoryByOrderNumber(
    int? workId,
    String? orderNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllInventoryByOrderNumber,
          [
            workId,
            orderNumber,
          ],
        ),
        returnValue: _i9.Future<List<_i13.Summary>>.value(<_i13.Summary>[]),
      ) as _i9.Future<List<_i13.Summary>>);

  @override
  _i9.Future<List<_i13.Summary>> getAllInventoryByPackage(
    int? workId,
    String? orderNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllInventoryByPackage,
          [
            workId,
            orderNumber,
          ],
        ),
        returnValue: _i9.Future<List<_i13.Summary>>.value(<_i13.Summary>[]),
      ) as _i9.Future<List<_i13.Summary>>);

  @override
  _i9.Future<List<_i13.Summary>> getAllPackageByOrderNumber(
    int? workId,
    String? orderNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPackageByOrderNumber,
          [
            workId,
            orderNumber,
          ],
        ),
        returnValue: _i9.Future<List<_i13.Summary>>.value(<_i13.Summary>[]),
      ) as _i9.Future<List<_i13.Summary>>);

  @override
  _i9.Future<List<_i13.Summary>> watchAllItemsPackage(
    String? orderNumber,
    String? packing,
    String? idPacking,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllItemsPackage,
          [
            orderNumber,
            packing,
            idPacking,
          ],
        ),
        returnValue: _i9.Future<List<_i13.Summary>>.value(<_i13.Summary>[]),
      ) as _i9.Future<List<_i13.Summary>>);

  @override
  _i9.Future<List<_i13.Summary>> getAllSummariesByOrderNumberMoved(
    int? workId,
    String? orderNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSummariesByOrderNumberMoved,
          [
            workId,
            orderNumber,
          ],
        ),
        returnValue: _i9.Future<List<_i13.Summary>>.value(<_i13.Summary>[]),
      ) as _i9.Future<List<_i13.Summary>>);

  @override
  _i9.Future<List<_i14.SummaryReport>> getSummaryReportsWithReasonOrRedelivery(
          String? orderNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSummaryReportsWithReasonOrRedelivery,
          [orderNumber],
        ),
        returnValue:
            _i9.Future<List<_i14.SummaryReport>>.value(<_i14.SummaryReport>[]),
      ) as _i9.Future<List<_i14.SummaryReport>>);

  @override
  _i9.Future<List<_i14.SummaryReport>> getSummaryReportsWithReturnOrRedelivery(
          String? orderNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSummaryReportsWithReturnOrRedelivery,
          [orderNumber],
        ),
        returnValue:
            _i9.Future<List<_i14.SummaryReport>>.value(<_i14.SummaryReport>[]),
      ) as _i9.Future<List<_i14.SummaryReport>>);

  @override
  _i9.Future<List<_i14.SummaryReport>> getSummaryReportsWithDelivery(
          String? orderNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSummaryReportsWithDelivery,
          [orderNumber],
        ),
        returnValue:
            _i9.Future<List<_i14.SummaryReport>>.value(<_i14.SummaryReport>[]),
      ) as _i9.Future<List<_i14.SummaryReport>>);

  @override
  _i9.Future<double> countTotalRespawnWorksByWorkcode(
    String? workcode,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #countTotalRespawnWorksByWorkcode,
          [
            workcode,
            reason,
          ],
        ),
        returnValue: _i9.Future<double>.value(0.0),
      ) as _i9.Future<double>);

  @override
  _i9.Future<bool> resetCantSummaries(
    int? workId,
    String? orderNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetCantSummaries,
          [
            workId,
            orderNumber,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<double> getTotalSummaries(
    int? workId,
    String? orderNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalSummaries,
          [
            workId,
            orderNumber,
          ],
        ),
        returnValue: _i9.Future<double>.value(0.0),
      ) as _i9.Future<double>);

  @override
  _i9.Future<int> getTotalPackageSummaries(String? orderNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalPackageSummaries,
          [orderNumber],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> getTotalPackageSummariesLoose(String? orderNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalPackageSummariesLoose,
          [orderNumber],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> insertSummary(_i13.Summary? summary) => (super.noSuchMethod(
        Invocation.method(
          #insertSummary,
          [summary],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateSummary(_i13.Summary? summary) => (super.noSuchMethod(
        Invocation.method(
          #updateSummary,
          [summary],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertSummaries(List<_i13.Summary>? summaries) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSummaries,
          [summaries],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptySummaries() => (super.noSuchMethod(
        Invocation.method(
          #emptySummaries,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteSummariesByWorkcode(String? workcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSummariesByWorkcode,
          [workcode],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i15.Transaction>> getAllTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTransactions,
          [],
        ),
        returnValue:
            _i9.Future<List<_i15.Transaction>>.value(<_i15.Transaction>[]),
      ) as _i9.Future<List<_i15.Transaction>>);

  @override
  _i9.Future<String?> getDiffTime(int? workId) => (super.noSuchMethod(
        Invocation.method(
          #getDiffTime,
          [workId],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<double?> countTotalCollectionWorks() => (super.noSuchMethod(
        Invocation.method(
          #countTotalCollectionWorks,
          [],
        ),
        returnValue: _i9.Future<double?>.value(),
      ) as _i9.Future<double?>);

  @override
  _i9.Future<int> insertTransaction(_i15.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTransaction,
          [transaction],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> insertTransactionSummary(
          _i16.TransactionSummary? transactionSummary) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTransactionSummary,
          [transactionSummary],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<bool> validateTransaction(int? workId) => (super.noSuchMethod(
        Invocation.method(
          #validateTransaction,
          [workId],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> validateTransactionArrived(
    int? workId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateTransactionArrived,
          [
            workId,
            status,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> validateTransactionSummary(
    String? workcode,
    String? orderNumber,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateTransactionSummary,
          [
            workcode,
            orderNumber,
            status,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> checkLastTransaction(String? workcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkLastTransaction,
          [workcode],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> checkLastProduct(int? transactionId) => (super.noSuchMethod(
        Invocation.method(
          #checkLastProduct,
          [transactionId],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<int> updateTransaction(_i15.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [transaction],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertTransactions(List<_i15.Transaction>? transactions) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTransactions,
          [transactions],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyTransactions() => (super.noSuchMethod(
        Invocation.method(
          #emptyTransactions,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteTransactionsByWorkcode(String? workcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTransactionsByWorkcode,
          [workcode],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<int> countLeftClients(String? workcode) => (super.noSuchMethod(
        Invocation.method(
          #countLeftClients,
          [workcode],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<double> countTotalCollectionWorksByWorkcode(String? workcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #countTotalCollectionWorksByWorkcode,
          [workcode],
        ),
        returnValue: _i9.Future<double>.value(0.0),
      ) as _i9.Future<double>);

  @override
  _i9.Future<bool> verifyTransactionExistence(
    int? workId,
    String? orderNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyTransactionExistence,
          [
            workId,
            orderNumber,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<List<_i17.Reason>> getAllReasons() => (super.noSuchMethod(
        Invocation.method(
          #getAllReasons,
          [],
        ),
        returnValue: _i9.Future<List<_i17.Reason>>.value(<_i17.Reason>[]),
      ) as _i9.Future<List<_i17.Reason>>);

  @override
  _i9.Future<_i17.Reason?> findReason(String? name) => (super.noSuchMethod(
        Invocation.method(
          #findReason,
          [name],
        ),
        returnValue: _i9.Future<_i17.Reason?>.value(),
      ) as _i9.Future<_i17.Reason?>);

  @override
  _i9.Future<int> insertReason(_i17.Reason? reason) => (super.noSuchMethod(
        Invocation.method(
          #insertReason,
          [reason],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateReason(_i17.Reason? reason) => (super.noSuchMethod(
        Invocation.method(
          #updateReason,
          [reason],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertReasons(List<_i17.Reason>? reasons) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertReasons,
          [reasons],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyReasons() => (super.noSuchMethod(
        Invocation.method(
          #emptyReasons,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i18.Account>> getAllAccounts() => (super.noSuchMethod(
        Invocation.method(
          #getAllAccounts,
          [],
        ),
        returnValue: _i9.Future<List<_i18.Account>>.value(<_i18.Account>[]),
      ) as _i9.Future<List<_i18.Account>>);

  @override
  _i9.Future<int> insertAccount(_i18.Account? account) => (super.noSuchMethod(
        Invocation.method(
          #insertAccount,
          [account],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateAccount(_i18.Account? account) => (super.noSuchMethod(
        Invocation.method(
          #updateAccount,
          [account],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertAccounts(List<_i18.Account>? accounts) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAccounts,
          [accounts],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyAccounts() => (super.noSuchMethod(
        Invocation.method(
          #emptyAccounts,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.ProcessingQueue>> getAllProcessingQueues(
    String? code,
    String? task,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProcessingQueues,
          [
            code,
            task,
          ],
        ),
        returnValue: _i9.Future<List<_i2.ProcessingQueue>>.value(
            <_i2.ProcessingQueue>[]),
      ) as _i9.Future<List<_i2.ProcessingQueue>>);

  @override
  _i9.Future<List<_i2.ProcessingQueue>> getAllProcessingQueuesPaginated(
    int? page,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProcessingQueuesPaginated,
          [
            page,
            limit,
          ],
        ),
        returnValue: _i9.Future<List<_i2.ProcessingQueue>>.value(
            <_i2.ProcessingQueue>[]),
      ) as _i9.Future<List<_i2.ProcessingQueue>>);

  @override
  _i9.Future<_i2.ProcessingQueue> findProcessingQueue(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #findProcessingQueue,
          [id],
        ),
        returnValue:
            _i9.Future<_i2.ProcessingQueue>.value(_FakeProcessingQueue_0(
          this,
          Invocation.method(
            #findProcessingQueue,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.ProcessingQueue>);

  @override
  _i9.Stream<List<_i2.ProcessingQueue>> watchAllProcessingQueues() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllProcessingQueues,
          [],
        ),
        returnValue: _i9.Stream<List<_i2.ProcessingQueue>>.empty(),
      ) as _i9.Stream<List<_i2.ProcessingQueue>>);

  @override
  _i9.Future<List<_i2.ProcessingQueue>> getAllProcessingQueuesIncomplete() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProcessingQueuesIncomplete,
          [],
        ),
        returnValue: _i9.Future<List<_i2.ProcessingQueue>>.value(
            <_i2.ProcessingQueue>[]),
      ) as _i9.Future<List<_i2.ProcessingQueue>>);

  @override
  _i9.Future<int> countProcessingQueueIncompleteToTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #countProcessingQueueIncompleteToTransactions,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Stream<List<Map<String, dynamic>>>
      getProcessingQueueIncompleteToTransactions() => (super.noSuchMethod(
            Invocation.method(
              #getProcessingQueueIncompleteToTransactions,
              [],
            ),
            returnValue: _i9.Stream<List<Map<String, dynamic>>>.empty(),
          ) as _i9.Stream<List<Map<String, dynamic>>>);

  @override
  _i9.Future<bool> validateIfProcessingQueueIsIncomplete() =>
      (super.noSuchMethod(
        Invocation.method(
          #validateIfProcessingQueueIsIncomplete,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<int> updateProcessingQueue(_i2.ProcessingQueue? processingQueue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProcessingQueue,
          [processingQueue],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> insertProcessingQueue(_i2.ProcessingQueue? processingQueue) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProcessingQueue,
          [processingQueue],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> emptyProcessingQueues() => (super.noSuchMethod(
        Invocation.method(
          #emptyProcessingQueues,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<List<_i19.Location>> watchAllLocations() => (super.noSuchMethod(
        Invocation.method(
          #watchAllLocations,
          [],
        ),
        returnValue: _i9.Stream<List<_i19.Location>>.empty(),
      ) as _i9.Stream<List<_i19.Location>>);

  @override
  _i9.Future<List<_i19.Location>> getAllLocations() => (super.noSuchMethod(
        Invocation.method(
          #getAllLocations,
          [],
        ),
        returnValue: _i9.Future<List<_i19.Location>>.value(<_i19.Location>[]),
      ) as _i9.Future<List<_i19.Location>>);

  @override
  _i9.Future<_i19.Location?> getLastLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLastLocation,
          [],
        ),
        returnValue: _i9.Future<_i19.Location?>.value(),
      ) as _i9.Future<_i19.Location?>);

  @override
  _i9.Future<bool> countLocationsManager() => (super.noSuchMethod(
        Invocation.method(
          #countLocationsManager,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<String> getLocationsToSend() => (super.noSuchMethod(
        Invocation.method(
          #getLocationsToSend,
          [],
        ),
        returnValue: _i9.Future<String>.value(_i20.dummyValue<String>(
          this,
          Invocation.method(
            #getLocationsToSend,
            [],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<int?> updateLocationsManager() => (super.noSuchMethod(
        Invocation.method(
          #updateLocationsManager,
          [],
        ),
        returnValue: _i9.Future<int?>.value(),
      ) as _i9.Future<int?>);

  @override
  _i9.Future<int> updateLocation(_i19.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [location],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertLocation(_i19.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertLocation,
          [location],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyLocations() => (super.noSuchMethod(
        Invocation.method(
          #emptyLocations,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i21.Photo>> getAllPhotos() => (super.noSuchMethod(
        Invocation.method(
          #getAllPhotos,
          [],
        ),
        returnValue: _i9.Future<List<_i21.Photo>>.value(<_i21.Photo>[]),
      ) as _i9.Future<List<_i21.Photo>>);

  @override
  _i9.Future<_i21.Photo?> findPhoto(String? path) => (super.noSuchMethod(
        Invocation.method(
          #findPhoto,
          [path],
        ),
        returnValue: _i9.Future<_i21.Photo?>.value(),
      ) as _i9.Future<_i21.Photo?>);

  @override
  _i9.Future<int> insertPhoto(_i21.Photo? photo) => (super.noSuchMethod(
        Invocation.method(
          #insertPhoto,
          [photo],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updatePhoto(_i21.Photo? photo) => (super.noSuchMethod(
        Invocation.method(
          #updatePhoto,
          [photo],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> deletePhoto(_i21.Photo? photo) => (super.noSuchMethod(
        Invocation.method(
          #deletePhoto,
          [photo],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> deleteAll(int? photoId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [photoId],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertPhotos(List<_i21.Photo>? photos) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPhotos,
          [photos],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyPhotos() => (super.noSuchMethod(
        Invocation.method(
          #emptyPhotos,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i22.Note>> getAllNotes() => (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [],
        ),
        returnValue: _i9.Future<List<_i22.Note>>.value(<_i22.Note>[]),
      ) as _i9.Future<List<_i22.Note>>);

  @override
  _i9.Future<_i22.Note?> findNote(String? zoneId) => (super.noSuchMethod(
        Invocation.method(
          #findNote,
          [zoneId],
        ),
        returnValue: _i9.Future<_i22.Note?>.value(),
      ) as _i9.Future<_i22.Note?>);

  @override
  _i9.Future<int> insertNote(_i22.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #insertNote,
          [note],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateNote(_i22.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> deleteNote(_i22.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [note],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertNotes(List<_i22.Note>? notes) => (super.noSuchMethod(
        Invocation.method(
          #insertNotes,
          [notes],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyNotes() => (super.noSuchMethod(
        Invocation.method(
          #emptyNotes,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i23.Error>> getAllErrors() => (super.noSuchMethod(
        Invocation.method(
          #getAllErrors,
          [],
        ),
        returnValue: _i9.Future<List<_i23.Error>>.value(<_i23.Error>[]),
      ) as _i9.Future<List<_i23.Error>>);

  @override
  _i9.Future<int> insertError(_i23.Error? error) => (super.noSuchMethod(
        Invocation.method(
          #insertError,
          [error],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateError(_i23.Error? error) => (super.noSuchMethod(
        Invocation.method(
          #updateError,
          [error],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> deleteError(_i23.Error? error) => (super.noSuchMethod(
        Invocation.method(
          #deleteError,
          [error],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertErrors(List<_i23.Error>? errors) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertErrors,
          [errors],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyErrors() => (super.noSuchMethod(
        Invocation.method(
          #emptyErrors,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<List<_i24.Client>> watchAllClients() => (super.noSuchMethod(
        Invocation.method(
          #watchAllClients,
          [],
        ),
        returnValue: _i9.Stream<List<_i24.Client>>.empty(),
      ) as _i9.Stream<List<_i24.Client>>);

  @override
  _i9.Future<List<_i24.Client>> getAllClients() => (super.noSuchMethod(
        Invocation.method(
          #getAllClients,
          [],
        ),
        returnValue: _i9.Future<List<_i24.Client>>.value(<_i24.Client>[]),
      ) as _i9.Future<List<_i24.Client>>);

  @override
  _i9.Future<bool> validateClient(int? id) => (super.noSuchMethod(
        Invocation.method(
          #validateClient,
          [id],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<int> insertClient(_i24.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #insertClient,
          [client],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateClient(_i24.Client? client) => (super.noSuchMethod(
        Invocation.method(
          #updateClient,
          [client],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> emptyClients() => (super.noSuchMethod(
        Invocation.method(
          #emptyClients,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<int> insertHistory(_i25.HistoryOrder? historyOrder) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertHistory,
          [historyOrder],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<_i25.HistoryOrder?> getHistoryOrder(
    String? workcode,
    int? zoneId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistoryOrder,
          [
            workcode,
            zoneId,
          ],
        ),
        returnValue: _i9.Future<_i25.HistoryOrder?>.value(),
      ) as _i9.Future<_i25.HistoryOrder?>);

  @override
  _i9.Future<bool> listenForTableChanges(
    String? table,
    String? column,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForTableChanges,
          [
            table,
            column,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i26.Database?> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i9.Future<_i26.Database?>.value(),
      ) as _i9.Future<_i26.Database?>);

  @override
  _i9.Future<int> insertNotification(_i27.PushNotification? notification) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertNotification,
          [notification],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<List<_i27.PushNotification>> getNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
        ),
        returnValue: _i9.Future<List<_i27.PushNotification>>.value(
            <_i27.PushNotification>[]),
      ) as _i9.Future<List<_i27.PushNotification>>);

  @override
  _i9.Future<void> updateNotification(
    int? notificationId,
    String? readAt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotification,
          [
            notificationId,
            readAt,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<int?> countAllUnreadNotifications() => (super.noSuchMethod(
        Invocation.method(
          #countAllUnreadNotifications,
          [],
        ),
        returnValue: _i9.Future<int?>.value(),
      ) as _i9.Future<int?>);

  @override
  _i9.Future<int> insertPolylines(
    String? workcode,
    List<_i28.LatLng>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPolylines,
          [
            workcode,
            data,
          ],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<List<_i28.LatLng>> getPolylines(String? workcode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPolylines,
          [workcode],
        ),
        returnValue: _i9.Future<List<_i28.LatLng>>.value(<_i28.LatLng>[]),
      ) as _i9.Future<List<_i28.LatLng>>);

  @override
  _i9.Future<void> deleteProcessingQueueByDays() => (super.noSuchMethod(
        Invocation.method(
          #deleteProcessingQueueByDays,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteLocationsByDays() => (super.noSuchMethod(
        Invocation.method(
          #deleteLocationsByDays,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteNotificationsByDays() => (super.noSuchMethod(
        Invocation.method(
          #deleteNotificationsByDays,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteTransactionByDays() => (super.noSuchMethod(
        Invocation.method(
          #deleteTransactionByDays,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [ApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRepository extends _i1.Mock implements _i29.ApiRepository {
  MockApiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.DataState<_i30.EnterpriseResponse>> getEnterprise(
          {required _i31.EnterpriseRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnterprise,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i30.EnterpriseResponse>>.value(
            _FakeDataState_1<_i30.EnterpriseResponse>(
          this,
          Invocation.method(
            #getEnterprise,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i30.EnterpriseResponse>>);

  @override
  _i9.Future<_i3.DataState<_i32.EnterpriseConfigResponse>> getConfigEnterprise(
          {required _i33.EnterpriseConfigRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConfigEnterprise,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.DataState<_i32.EnterpriseConfigResponse>>.value(
                _FakeDataState_1<_i32.EnterpriseConfigResponse>(
          this,
          Invocation.method(
            #getConfigEnterprise,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i32.EnterpriseConfigResponse>>);

  @override
  _i9.Future<_i3.DataState<_i34.ReasonResponse>> reasons(
          {required _i35.ReasonRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reasons,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i34.ReasonResponse>>.value(
            _FakeDataState_1<_i34.ReasonResponse>(
          this,
          Invocation.method(
            #reasons,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i34.ReasonResponse>>);

  @override
  _i9.Future<_i3.DataState<_i36.AccountResponse>> accounts(
          {required _i37.AccountRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #accounts,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i36.AccountResponse>>.value(
            _FakeDataState_1<_i36.AccountResponse>(
          this,
          Invocation.method(
            #accounts,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i36.AccountResponse>>);

  @override
  _i9.Future<_i3.DataState<_i38.LoginResponse>?> login(
          {required _i39.LoginRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i38.LoginResponse>?>.value(),
      ) as _i9.Future<_i3.DataState<_i38.LoginResponse>?>);

  @override
  _i9.Future<_i3.DataState<_i40.LogoutResponse>> logout(
          {required _i41.LogoutRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i40.LogoutResponse>>.value(
            _FakeDataState_1<_i40.LogoutResponse>(
          this,
          Invocation.method(
            #logout,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i40.LogoutResponse>>);

  @override
  _i9.Future<_i3.DataState<_i42.WorkResponse>> works(
          {required _i43.WorkRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #works,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i42.WorkResponse>>.value(
            _FakeDataState_1<_i42.WorkResponse>(
          this,
          Invocation.method(
            #works,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i42.WorkResponse>>);

  @override
  _i9.Future<_i3.DataState<_i44.DatabaseResponse>> database(
          {required _i45.DatabaseRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #database,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i44.DatabaseResponse>>.value(
            _FakeDataState_1<_i44.DatabaseResponse>(
          this,
          Invocation.method(
            #database,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i44.DatabaseResponse>>);

  @override
  _i9.Future<_i3.DataState<_i46.StatusResponse>?> status(
          {required _i47.StatusRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #status,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i46.StatusResponse>?>.value(),
      ) as _i9.Future<_i3.DataState<_i46.StatusResponse>?>);

  @override
  _i9.Future<_i3.DataState<_i48.TransactionResponse>?> start(
          {required _i49.TransactionRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.DataState<_i48.TransactionResponse>?>.value(),
      ) as _i9.Future<_i3.DataState<_i48.TransactionResponse>?>);

  @override
  _i9.Future<_i3.DataState<_i48.TransactionResponse>?> arrived(
          {required _i49.TransactionRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #arrived,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.DataState<_i48.TransactionResponse>?>.value(),
      ) as _i9.Future<_i3.DataState<_i48.TransactionResponse>?>);

  @override
  _i9.Future<_i3.DataState<_i48.TransactionResponse>?> summary(
          {required _i49.TransactionRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #summary,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.DataState<_i48.TransactionResponse>?>.value(),
      ) as _i9.Future<_i3.DataState<_i48.TransactionResponse>?>);

  @override
  _i9.Future<_i3.DataState<_i48.TransactionResponse>?> index(
          {required _i49.TransactionRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #index,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.DataState<_i48.TransactionResponse>?>.value(),
      ) as _i9.Future<_i3.DataState<_i48.TransactionResponse>?>);

  @override
  _i9.Future<_i3.DataState<_i48.TransactionResponse>?> transaction(
          {required _i50.TransactionSummaryRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.DataState<_i48.TransactionResponse>?>.value(),
      ) as _i9.Future<_i3.DataState<_i48.TransactionResponse>?>);

  @override
  _i9.Future<_i3.DataState<_i51.TransactionSummaryResponse>?> product(
          {required _i50.TransactionSummaryRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #product,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.DataState<_i51.TransactionSummaryResponse>?>.value(),
      ) as _i9.Future<_i3.DataState<_i51.TransactionSummaryResponse>?>);

  @override
  _i9.Future<_i3.DataState<_i46.StatusResponse>> georeference(
          {required _i52.ClientRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #georeference,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i46.StatusResponse>>.value(
            _FakeDataState_1<_i46.StatusResponse>(
          this,
          Invocation.method(
            #georeference,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i46.StatusResponse>>);

  @override
  _i9.Future<_i3.DataState<_i46.StatusResponse>> sendFCMToken(
          {required _i53.SendTokenRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFCMToken,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i46.StatusResponse>>.value(
            _FakeDataState_1<_i46.StatusResponse>(
          this,
          Invocation.method(
            #sendFCMToken,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i46.StatusResponse>>);

  @override
  _i9.Future<_i3.DataState<_i54.PredictionResponse>> prediction(
          {required _i55.PredictionRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #prediction,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i54.PredictionResponse>>.value(
            _FakeDataState_1<_i54.PredictionResponse>(
          this,
          Invocation.method(
            #prediction,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i54.PredictionResponse>>);

  @override
  _i9.Future<_i3.DataState<_i56.HistoryOrderSavedResponse>> historyOrderSaved(
          {required _i57.HistoryOrderSavedRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #historyOrderSaved,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.DataState<_i56.HistoryOrderSavedResponse>>.value(
                _FakeDataState_1<_i56.HistoryOrderSavedResponse>(
          this,
          Invocation.method(
            #historyOrderSaved,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i56.HistoryOrderSavedResponse>>);

  @override
  _i9.Future<_i3.DataState<_i58.RoutingResponse>> routing(
          {required _i59.RoutingRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #routing,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i58.RoutingResponse>>.value(
            _FakeDataState_1<_i58.RoutingResponse>(
          this,
          Invocation.method(
            #routing,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i58.RoutingResponse>>);

  @override
  _i9.Future<
      _i3.DataState<_i60.HistoryOrderUpdatedResponse>> historyOrderUpdated(
          {required _i61.HistoryOrderUpdatedRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #historyOrderUpdated,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.DataState<_i60.HistoryOrderUpdatedResponse>>.value(
                _FakeDataState_1<_i60.HistoryOrderUpdatedResponse>(
          this,
          Invocation.method(
            #historyOrderUpdated,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i60.HistoryOrderUpdatedResponse>>);

  @override
  _i9.Future<_i3.DataState<_i46.StatusResponse>> locations(
          {required _i62.LocationsRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #locations,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i46.StatusResponse>>.value(
            _FakeDataState_1<_i46.StatusResponse>(
          this,
          Invocation.method(
            #locations,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i46.StatusResponse>>);

  @override
  _i9.Future<_i3.DataState<_i46.StatusResponse>> reason(
          {required _i63.ReasonMRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reason,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i3.DataState<_i46.StatusResponse>>.value(
            _FakeDataState_1<_i46.StatusResponse>(
          this,
          Invocation.method(
            #reason,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.DataState<_i46.StatusResponse>>);
}

/// A class which mocks [ProcessingQueueBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessingQueueBloc extends _i1.Mock
    implements _i5.ProcessingQueueBloc {
  MockProcessingQueueBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.HelperFunctions get helperFunctions => (super.noSuchMethod(
        Invocation.getter(#helperFunctions),
        returnValue: _FakeHelperFunctions_2(
          this,
          Invocation.getter(#helperFunctions),
        ),
      ) as _i4.HelperFunctions);

  @override
  List<Map<String, String>> get itemsFilter => (super.noSuchMethod(
        Invocation.getter(#itemsFilter),
        returnValue: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  List<Map<String, String>> get itemsState => (super.noSuchMethod(
        Invocation.getter(#itemsState),
        returnValue: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  _i9.Stream<dynamic> get resolve => (super.noSuchMethod(
        Invocation.getter(#resolve),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<List<_i2.ProcessingQueue>> get todos => (super.noSuchMethod(
        Invocation.getter(#todos),
        returnValue: _i9.Stream<List<_i2.ProcessingQueue>>.empty(),
      ) as _i9.Stream<List<_i2.ProcessingQueue>>);

  @override
  _i5.ProcessingQueueState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeProcessingQueueState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.ProcessingQueueState);

  @override
  _i9.Stream<_i5.ProcessingQueueState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i5.ProcessingQueueState>.empty(),
      ) as _i9.Stream<_i5.ProcessingQueueState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<int> countProcessingQueueIncompleteToTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #countProcessingQueueIncompleteToTransactions,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Stream<List<Map<String, dynamic>>>
      getProcessingQueueIncompleteToTransactions() => (super.noSuchMethod(
            Invocation.method(
              #getProcessingQueueIncompleteToTransactions,
              [],
            ),
            returnValue: _i9.Stream<List<Map<String, dynamic>>>.empty(),
          ) as _i9.Stream<List<Map<String, dynamic>>>);

  @override
  _i9.Future<List<_i2.ProcessingQueue>> getData(
    int? page,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [
            page,
            limit,
          ],
        ),
        returnValue: _i9.Future<List<_i2.ProcessingQueue>>.value(
            <_i2.ProcessingQueue>[]),
      ) as _i9.Future<List<_i2.ProcessingQueue>>);

  @override
  void sendProcessingQueues(List<_i2.ProcessingQueue>? queues) =>
      super.noSuchMethod(
        Invocation.method(
          #sendProcessingQueues,
          [queues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendProcessingQueue(_i2.ProcessingQueue? queue) => super.noSuchMethod(
        Invocation.method(
          #sendProcessingQueue,
          [queue],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> validateIfServiceIsCompleted(_i2.ProcessingQueue? p) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateIfServiceIsCompleted,
          [p],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void add(_i5.ProcessingQueueEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i5.ProcessingQueueEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.ProcessingQueueState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i5.ProcessingQueueEvent>(
    _i64.EventHandler<E, _i5.ProcessingQueueState>? handler, {
    _i64.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i64.Transition<_i5.ProcessingQueueEvent, _i5.ProcessingQueueState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void onChange(_i64.Change<_i5.ProcessingQueueState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String now() => (super.noSuchMethod(
        Invocation.method(
          #now,
          [],
        ),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.method(
            #now,
            [],
          ),
        ),
      ) as String);

  @override
  String date(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #date,
          [date],
        ),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.method(
            #date,
            [date],
          ),
        ),
      ) as String);
}

/// A class which mocks [GpsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGpsBloc extends _i1.Mock implements _i6.GpsBloc {
  MockGpsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set gpsServiceSubscription(
          _i9.StreamSubscription<dynamic>? _gpsServiceSubscription) =>
      super.noSuchMethod(
        Invocation.setter(
          #gpsServiceSubscription,
          _gpsServiceSubscription,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set positionStream(_i9.StreamSubscription<dynamic>? _positionStream) =>
      super.noSuchMethod(
        Invocation.setter(
          #positionStream,
          _positionStream,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get showingDialog => (super.noSuchMethod(
        Invocation.getter(#showingDialog),
        returnValue: false,
      ) as bool);

  @override
  set showingDialog(bool? _showingDialog) => super.noSuchMethod(
        Invocation.setter(
          #showingDialog,
          _showingDialog,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Stream<List<_i19.Location>> get locations => (super.noSuchMethod(
        Invocation.getter(#locations),
        returnValue: _i9.Stream<List<_i19.Location>>.empty(),
      ) as _i9.Stream<List<_i19.Location>>);

  @override
  _i6.GpsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGpsState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.GpsState);

  @override
  _i9.Stream<_i6.GpsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i6.GpsState>.empty(),
      ) as _i9.Stream<_i6.GpsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> startFollowingUser() => (super.noSuchMethod(
        Invocation.method(
          #startFollowingUser,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void stopFollowingUser() => super.noSuchMethod(
        Invocation.method(
          #stopFollowingUser,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> askGpsAccess() => (super.noSuchMethod(
        Invocation.method(
          #askGpsAccess,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  double calculateDistanceBetweenTwoLatLng(
    _i28.LatLng? currentPosition,
    _i28.LatLng? radiusPosition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateDistanceBetweenTwoLatLng,
          [
            currentPosition,
            radiusPosition,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  int calculateDateBetweenTwoLatLng(
    DateTime? date1,
    DateTime? date2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateDateBetweenTwoLatLng,
          [
            date1,
            date2,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool calculateRadiusBetweenTwoLatLng(
    _i28.LatLng? currentPosition,
    _i28.LatLng? radiusPosition,
    double? radius,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRadiusBetweenTwoLatLng,
          [
            currentPosition,
            radiusPosition,
            radius,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> saveLocation(
    String? type,
    _i65.Position? position,
    int? send,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocation,
          [
            type,
            position,
            send,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void add(_i6.GpsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.GpsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.GpsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.GpsEvent>(
    _i64.EventHandler<E, _i6.GpsState>? handler, {
    _i64.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i64.Transition<_i6.GpsEvent, _i6.GpsState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i64.Change<_i6.GpsState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String now() => (super.noSuchMethod(
        Invocation.method(
          #now,
          [],
        ),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.method(
            #now,
            [],
          ),
        ),
      ) as String);

  @override
  String date(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #date,
          [date],
        ),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.method(
            #date,
            [date],
          ),
        ),
      ) as String);
}

/// A class which mocks [NetworkBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkBloc extends _i1.Mock implements _i7.NetworkBloc {
  MockNetworkBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.NetworkState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeNetworkState_5(
          this,
          Invocation.getter(#state),
        ),
      ) as _i7.NetworkState);

  @override
  _i9.Stream<_i7.NetworkState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i7.NetworkState>.empty(),
      ) as _i9.Stream<_i7.NetworkState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i7.NetworkEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i7.NetworkEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i7.NetworkState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i7.NetworkEvent>(
    _i64.EventHandler<E, _i7.NetworkState>? handler, {
    _i64.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i64.Transition<_i7.NetworkEvent, _i7.NetworkState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void onChange(_i64.Change<_i7.NetworkState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
