name: location_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
dependencies:
  location:
    git:
      url: https://github.com/fairuzmn/flutterlocation.git
      ref: location-v5.5.0.0-dev.9-fix
      path: packages/location
