name: Android Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  version:
    name: Version Number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Retrieve Tags and Branch History
#        run: |
#          git config remote.origin.url https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}
#          git fetch --prune --depth=10000
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.5.1"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Creating version.txt with nuGetVersion
        run: echo ${{steps.gitversion.outputs.nuGetVersion}} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt